/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import clases.conexionBaseDatos;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jose
 */
public class frmRecepcionista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmRecepcionista.class.getName());
    private conexionBaseDatos conexion;
    
    /**
     * Creates new form frmRecepcionista
     */
    public frmRecepcionista() throws SQLException {
        initComponents();
        conexion =new conexionBaseDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabCitas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabPacientes = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTabDoctores = new javax.swing.JTable();
        jButCitas = new javax.swing.JButton();
        jButPacientes = new javax.swing.JButton();
        jButDoctores = new javax.swing.JButton();
        jButPacientesAgregar = new javax.swing.JButton();
        jButPacienteEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Recepcionista");

        jTabCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTabCitas);

        jTabPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTabPacientes);

        jTabDoctores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTabDoctores);

        jButCitas.setText("Refrescar Citas");
        jButCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCitasActionPerformed(evt);
            }
        });

        jButPacientes.setText("Refrescar Pacientes");
        jButPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButPacientesActionPerformed(evt);
            }
        });

        jButDoctores.setText("Refrescar Doctores");
        jButDoctores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDoctoresActionPerformed(evt);
            }
        });

        jButPacientesAgregar.setText("Agregar paciente nuevo ");
        jButPacientesAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButPacientesAgregarActionPerformed(evt);
            }
        });

        jButPacienteEliminar.setText("Eliminar paciente");
        jButPacienteEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButPacienteEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButCitas))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButPacientes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButPacientesAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButPacienteEliminar))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButDoctores))
                .addContainerGap(525, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButCitas)
                    .addComponent(jButPacientes)
                    .addComponent(jButPacientesAgregar)
                    .addComponent(jButPacienteEliminar))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButDoctores, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCitasActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel modelo=new DefaultTableModel();
        String query="SELECT \n" +
        "    c.id_cita,\n" +
        "    TO_CHAR(c.fecha, 'DD/MM/YYYY HH24:MI') as fecha_hora, -- Formato legible\n" +
        "    p.nombre AS nombre_paciente,\n" +
        "    u.nombre AS nombre_doctor,\n" +
        "    d.especialidad,\n" +
        "    c.estado\n" +
        "FROM \n" +
        "    APLICACION.Cita c\n" +
        "JOIN \n" +
        "    APLICACION.Paciente p ON c.id_paciente = p.id_paciente\n" +
        "JOIN \n" +
        "    APLICACION.Doctor d ON c.id_doctor = d.id_doctor\n" +
        "JOIN \n" +
        "    APLICACION.Usuario u ON d.id_usuario = u.id_usuario\n" +
        "ORDER BY \n" +
        "    c.fecha DESC;";
        //Cambias el texto por lo que quieras cargar
        modelo=conexion.getTableModel(query);
        this.jTabCitas.setModel(modelo);
        
    }//GEN-LAST:event_jButCitasActionPerformed

    private void jButPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButPacientesActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel modelo=new DefaultTableModel();
        String query="""
                     SELECT id_paciente,
                                nombre,
                                TO_CHAR(fecha_nacimiento, 'DD/MM/YYYY') AS fecha_nacimiento,
                                telefono,
                                correo,
                                direccion
                         FROM APLICACION.Paciente
                         ORDER BY nombre ASC
                     """;
        //Cambias el texto por lo que quieras cargar
        modelo=conexion.getTableModel(query);
        this.jTabPacientes.setModel(modelo);
        
    }//GEN-LAST:event_jButPacientesActionPerformed

    private void jButDoctoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDoctoresActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel modelo=new DefaultTableModel();
        String query="""
                     SELECT d.id_doctor,
                                u.nombre AS nombre_doctor,
                                d.especialidad,
                                d.cedula_profesional,
                                d.horario
                         FROM Doctor d
                         JOIN Usuario u ON d.id_usuario = u.id_usuario
                         ORDER BY u.nombre ASC
                     """;
        //Cambias el texto por lo que quieras cargar
        modelo=conexion.getTableModel(query);
        this.jTabPacientes.setModel(modelo);
        
    }//GEN-LAST:event_jButDoctoresActionPerformed

    private void jButPacientesAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButPacientesAgregarActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jButPacientesAgregarActionPerformed

    private void jButPacienteEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButPacienteEliminarActionPerformed
        // TODO add your handling code here:
        
            // 1. Verificar si seleccionó una fila
        int fila = jTabPacientes.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona un registro primero");
            return;
        }

        // 2. Pedir confirmación
        int confirmacion = JOptionPane.showConfirmDialog(this, 
            "¿Seguro que deseas eliminar este registro? Este registro puede borrar otros que dependen de el como citas", 
            "Confirmar Borrado", 
            JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            // 3. Obtener el ID (OJO: Asumiendo que el ID es la columna 0)
            String idStr = jTabPacientes.getValueAt(fila, 0).toString();
            int id = Integer.parseInt(idStr);

            // 4. Mandar a borrar en Hilo Virtual (Java 21)
            
                try {
                    // Llama a tu método DELETE en el DAO
                    boolean exito=conexion.ejecutarSQL("delete from paciente where id ="+id+" cascade");
                    
                    if(exito){
                        // Actualizar tabla en hilo visual
                        SwingUtilities.invokeLater(() -> {
                        JOptionPane.showMessageDialog(this, "Eliminado correctamente");
                        });
                    }
                    
                } catch (Exception e) {
                    SwingUtilities.invokeLater(() -> 
                        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage()));
                }
            
        }
        
    }//GEN-LAST:event_jButPacienteEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new frmRecepcionista().setVisible(true);
            } catch (SQLException ex) {
                System.getLogger(frmRecepcionista.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButCitas;
    private javax.swing.JButton jButDoctores;
    private javax.swing.JButton jButPacienteEliminar;
    private javax.swing.JButton jButPacientes;
    private javax.swing.JButton jButPacientesAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTabCitas;
    private javax.swing.JTable jTabDoctores;
    private javax.swing.JTable jTabPacientes;
    // End of variables declaration//GEN-END:variables
}
