/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.dialogs;

import clases.conexionBaseDatos;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;

/**
 *
 * @author jose
 */
public class jDialogDoctores extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jDialogDoctores.class.getName());
    private int idDoctorActual = 0;

    private conexionBaseDatos conexion;
    
    /**
     * Creates new form jDialogPacientes
     */
    public jDialogDoctores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public jDialogDoctores(java.awt.Frame parent, boolean modal,int id) {
        super(parent, modal);
        initComponents();
        
        this.idDoctorActual = id;// Guardamos el ID
        
        try {
            conexion = new conexionBaseDatos(); // Preparamos la conexión
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error de conexión: " + e.getMessage());
        }

        // Lógica para decidir qué mostrar
        if (idDoctorActual > 0) {
            // MODO EDICIÓN
            lblTitulo.setText("EDITAR DOCTOR");
            btnGuardar.setText("Actualizar");
            cargarDatosParaEditar(idDoctorActual); // Llenamos los campos
        } else {
            // MODO CREACIÓN
            lblTitulo.setText("NUEVO DOCTOR");
            btnGuardar.setText("Guardar");
            // Los campos aparecen vacíos por defecto
        }
    }

    private void cargarDatosParaEditar(int id) {
        String sql = "SELECT id_usuario, especialidad, cedula_profesional, horario\n" +
"FROM doctor\n" +
"WHERE id_doctor = " + id;
        
        try (Connection conn = conexion.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            if (rs.next()) {
                // Asumiendo que tus variables se llaman txtNombre, txtTelefono, etc.
                txtFecha.setText(rs.getString("id_usuario"));
                txtTelefono.setText(rs.getString("especialidad"));
                txtCorreo.setText(rs.getString("cedula_profesional"));
                txtDireccion.setText(rs.getString("horario"));
                // 1. Obtienes la fecha de Oracle
            java.sql.Date fechaBD = rs.getDate("fecha_nacimiento");

            // 2. La conviertes a Texto bonito (String)
            if (fechaBD != null) {
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                String fechaTexto = sdf.format(fechaBD); 

                // 3. Ahora sí usas setText
                txtTelefono.setText(fechaTexto); // Se verá "25/12/2000"
            } else {
                txtTelefono.setText(""); // Si es null, lo dejas vacío
            }
            if (fechaBD != null) {
                txtTelefono.setText(fechaBD.toString()); 
            }
            // ---------------------------
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar datos: " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        txtFecha = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jButCancelar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Especialidad");

        jLabel3.setText("Cedula");

        jLabel4.setText("Horario");

        btnGuardar.setText("Insertar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        jLabel5.setText("ID-Usuario");

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        jButCancelar.setText("Cancelar");
        jButCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCancelarActionPerformed(evt);
            }
        });

        lblTitulo.setText("Doctores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(lblTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitulo)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(17, 17, 17)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel5)
                                .addGap(67, 67, 67)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCancelarActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_jButCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
            
    // --- 1. VALIDACIONES BÁSICAS ---
    // Verificamos que los campos obligatorios (Nombre y Fecha) no estén vacíos
    if (txtFecha.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "El ID de Usuario es obligatorio.");
        return;
    }
    if (txtFecha.getText().trim().isEmpty() ||
    txtTelefono.getText().trim().isEmpty() ||
    txtCorreo.getText().trim().isEmpty() ||
    txtDireccion.getText().trim().isEmpty()) {

    JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios");
    return;
}

    
    // --- 2. OBTENER DATOS DEL FORMULARIO ---
    int idUsuario = Integer.parseInt(txtFecha.getText().trim());
    String especialidad = txtTelefono.getText().trim();
    String cedula = txtCorreo.getText().trim();
    String horario = txtDireccion.getText().trim();


    // --- 3. PREPARAR LA FECHA PARA ORACLE ---
    // Usamos TO_DATE para convertir el texto '25/12/2000' a formato fecha real
    

    String sql;

if (idDoctorActual == 0) {
    // INSERTAR
    sql = "INSERT INTO doctor (" +
          "id_doctor, id_usuario, especialidad, cedula_profesional, horario) " +
          "VALUES (" +
          "seq_doctor.NEXTVAL, " +
          idUsuario + ", " +
          "'" + especialidad + "', " +
          "'" + cedula + "', " +
          "'" + horario + "')";
} else {
    // ACTUALIZAR
    sql = "UPDATE doctor SET " +
          "id_usuario = " + idUsuario + ", " +
          "especialidad = '" + especialidad + "', " +
          "cedula_profesional = '" + cedula + "', " +
          "horario = '" + horario + "' " +
          "WHERE id_doctor = " + idDoctorActual;
}



    // --- 5. EJECUTAR ---
    // Si la fecha está mal escrita (ej: "32/13/2020"), Oracle dará error y entrará al else
    if (conexion.ejecutarSQL(sql)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Datos guardados correctamente.");
        this.dispose(); // Cerramos la ventana para volver a la tabla principal
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Error al guardar.\nVerifica que la fecha tenga el formato dd/mm/yyyy (Ej: 25/12/2000).", 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }

        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                jDialogDoctores dialog = new jDialogDoctores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButCancelar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
